### ISSUE TITLE
Missing files after installation

### ISSUE THREAD

**Issue by vinicius5581** [bleutzinn/grav-plugin-editable#4]
I've installed this plugin using gpm and .zip files. In both cases I'm getting errors about missing files.

<img width="1432" alt="screen shot 2017-03-11 at 6 12 24 pm" src="https://cloud.githubusercontent.com/assets/1258955/23828681/a7cc11de-068e-11e7-9834-72c82a824ebf.png">

If i run the following command I get nothing back.

find /home/ubuntu/gravcms/ -name "simplemdeshortcode.php"

**Comment by OleVik** [comment]
As stated in the [README](https://github.com/bleutzinn/grav-plugin-editable/tree/v1.0.0#add-ons-), Editable is the core. You must install one of the add-ons for functionality, in your case [SimpleMDE](https://github.com/bleutzinn/editable-simplemde-add-on). @bleutzinn, maybe throw an exception within the plugin if no editors are found?

**Comment by bleutzinn** [comment]
@OleVik, yes you are right and thanks for the answer and suggestion.
@vinicius5581, you need to download the SimpleMDE Addon from https://github.com/bleutzinn/editable-simplemde-add-on
Follow the instructions in [that ReadMe](https://github.com/bleutzinn/editable-simplemde-add-on/blob/master/README.md) to install the addon.
The plugin should indeed prompt or warn the user when there is no editor addon installed or when the configuration refers to a missing add-on.

**Comment by vinicius5581** [comment]
Got it. Thanks guys. It's working as it should now. Should I close this issue or keep it open to handle the exception suggested by @bleutzinn?

**Comment by bleutzinn** [comment]
This will be handled better in the first major update of Editable.
