### ISSUE TITLE
Cannot save edit 2 levels deep

### ISSUE THREAD

**Issue by kyles-repository** [bleutzinn/grav-plugin-editable#5]
Hi, just checking up. I am not able to save after editing if the file is 2 levels deep. _Is this an issue, or just me_?

Error:

`
Call to undefined method Grav\Plugin\EditablePlugin::setErrorCode() in /home/grav-admin/user/plugins/editable/editable.php on line 155
`

Didn't do much tracing, neither have I read the source code, but I'm not trying to bash, but it seems like the code below does not function, undefined call to setErrorCode couldn't find another usage in editable.php, same with buildReturnMessage.

`
        if ($page == null) {
            // Page does not exist
            $this->setErrorCode(404);
            $message = $this->buildReturnMessage('Page does not exist.');
            return $message;
        }
`

Can't be of much help, all my text editors are not functioning (non related to this issue - just a slight rant).

Oh example folder structure 

/pages
/01.home
-- default.md
-- /item1
-- --default.md

pages/01.home/item1/default.md edits could not be saved

**Comment by kyles-repository** [comment]
https://github.com/kyles-repository/grav-plugin-editable did a fork of your plugin and patched it. I'm not sure if its valuable as a fix but if it is I'd be grateful to be apart of the patching process if you go slow with me. Particularly would like the credits ;D . Very simple 3 portions of changes. The rest seems to be window - linux line endings?

**Comment by bleutzinn** [comment]
Should be fixed in the latest release.
