### ISSUE TITLE
Doesn't work with modulars

### ISSUE THREAD

**Issue by mpetricek** [bleutzinn/grav-plugin-editable#8]
Hi,

plugin is great but it is not working with modular pages for me.

I have for editable divs straight under navigation div. But the modular divs are not getting the much needed classes. Is there way to solve it? Thank you

` <div data-editable data-name="editable___">
	<div data-editable data-name="editable___">
	<div data-editable data-name="editable___">
	<div data-editable data-name="editable___">
	
</div>

</div>

</div>

</div>`

**Comment by bleutzinn** [comment]
Technically Editable works with modular pages. However modular pages are intended not to contain simple markdown or HTML. Modular pages typically contain or assemble content dynamically from other content. Usually through a collection.
Editable can only edit static content that is present in the page filesystem file (the `default.md` file.

Another possible cause is the theme in use. At the moment only Antimatter is supported and other theme might work or not. That depends on the available templates. For example, it seems that Editable and the GravStrap theme are not compatible.
